<a href="https://colab.research.google.com/github/FahmidaNourin/CSE445_Machine_Learning/blob/main/Project_Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#connecting with drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#read in csv file

In [ ]:
import numpy as np
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/Sleep_Research/HMC_Sleep_Stages.csv")

In [ ]:
df.head()

Subject Sleep_Stage  Epoch  MeanP_Alpha_F4  MedianF_Alpha_F4  \
0   SN002          N1      6         0.00034          10.11512   
1   SN002          N1      7         0.00035          10.73951   
2   SN002          N1      8         0.00035           9.36585   
3   SN002          N1    116         0.00054           9.74049   
4   SN002          N1    117         0.00034          10.11512   

   MeanF_Alpha_F4  SpectralEdge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0        17.85756               17.48293        10.24000        0.00047   
1        17.60780               17.10829         9.11610        0.00048   
2        17.60780               16.98341         9.24098        0.00042   
3        15.98439               15.48488         8.36683        0.00051   
4        16.48390               15.98439        12.23805        0.00034   

   MedianF_Beta_F4  ...  MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0         17.73268  ...         0.00112           0.74927         6.36878   
1         16.85854  ...         0.00070           0.99902         6.86829   
2         17.35805  ...         0.00077           1.49854         6.49366   
3         14.61073  ...         0.00082           0.87415         7.49268   
4         15.11024  ...         0.00084           0.87415         6.86829   

   SpectralEdge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  \
0                2.87220         0.62439        0.000076          32.71805   
1                3.62146         0.74927        0.000072          32.09366   
2                4.12098         0.74927        0.000069          33.09268   
3                3.49659         0.87415        0.000039          28.34732   
4                2.87220         0.62439        0.000032          28.97171   

   MeanF_Gamma_O2  SpectralEdge_Gamma_O2  PeakF_Gamma_O2  
0        43.83220               49.95122        49.95122  
1        44.33171               49.95122        49.95122  
2        43.95707               49.95122        49.95122  
3        43.08293               49.95122        49.95122  
4        43.20780               49.95122        49.95122  

[5 rows x 78 columns]

In [ ]:
df = df.dropna().reset_index(drop=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108451 entries, 0 to 108450
Data columns (total 78 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Subject                108451 non-null  object 
 1   Sleep_Stage            108451 non-null  object 
 2   Epoch                  108451 non-null  int64  
 3   MeanP_Alpha_F4         108451 non-null  float64
 4   MedianF_Alpha_F4       108451 non-null  float64
 5   MeanF_Alpha_F4         108451 non-null  float64
 6   SpectralEdge_Alpha_F4  108451 non-null  float64
 7   PeakF_Alpha_F4         108451 non-null  float64
 8   MeanP_Beta_F4          108451 non-null  float64
 9   MedianF_Beta_F4        108451 non-null  float64
 10  MeanF_Beta_F4          108451 non-null  float64
 11  SpectralEdge_Beta_F4   108451 non-null  float64
 12  PeakF_Beta_F4          108451 non-null  float64
 13  MeanP_Theta_F4         108451 non-null  float64
 14  MedianF_Theta_F4       108451 non-nu

#Converting N1,N2 -> Light_Sleep, N3 -> Deep_Sleep And removing W stage.

In [ ]:
df.shape

(108451, 78)

In [ ]:
df =df.replace("N1", "Light_Sleep")
df =df.replace("N2", "Light_Sleep")
df =df.replace("N3", "Deep_Sleep")
df =df.replace("R", "REM")
df.drop(df.index[df['Sleep_Stage'] == "W"], inplace = True)


In [ ]:
df.shape

(89096, 78)

In [ ]:
df = df.loc[:,df.columns != "Subject"]
df = df.loc[:,df.columns != "Epoch"]

In [ ]:
target="Sleep_Stage"

In [ ]:
df["Sleep_Stage"].value_counts()

Light_Sleep    51341
Deep_Sleep     21290
REM            16465
Name: Sleep_Stage, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
encd = LabelEncoder()

In [ ]:
df["Sleep_Stage"] = encd.fit_transform(df["Sleep_Stage"])

In [ ]:
df["Sleep_Stage"].value_counts()

1    39428
2    21290
4    19355
3    16465
0    11913
Name: Sleep_Stage, dtype: int64

In [ ]:
target="Sleep_Stage"

In [ ]:
X = df.loc[:,df.columns != target]
y = df[target]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20)

In [ ]:
y_train.value_counts()

1    31511
2    17019
4    15517
3    13173
0     9540
Name: Sleep_Stage, dtype: int64

**<font color='red'>SNB:</font><font color='olive'> We used *SMOTE* in train data only, so that our test data can remain corrupted data free. The accurecy of the model will be counted only for actual data.</font>**

In [ ]:
!pip install imbalanced-learn

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train,y_train = smote.fit_resample(X_train,y_train)

In [ ]:
y_train.value_counts()

0    31511
2    31511
3    31511
1    31511
4    31511
Name: Sleep_Stage, dtype: int64

In [ ]:
y_test.value_counts()

1    7917
2    4271
4    3838
3    3292
0    2373
Name: Sleep_Stage, dtype: int64

# tree

In [ ]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[5498  746   97  703  814]
 [ 940 4850 1068  687  245]
 [ 201  931 6670   68   49]
 [ 829  538   71 6331  156]
 [ 973  261   48  179 6475]]
              precision    recall  f1-score   support

           0       0.65      0.70      0.67      7858
           1       0.66      0.62      0.64      7790
           2       0.84      0.84      0.84      7919
           3       0.79      0.80      0.80      7925
           4       0.84      0.82      0.83      7936

    accuracy                           0.76     39428
   macro avg       0.76      0.76      0.76     39428
weighted avg       0.76      0.76      0.76     39428

Accurecy:  0.7564167596631836


#RandomForest

In [ ]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

CPU times: user 2min 50s, sys: 437 ms, total: 2min 51s
Wall time: 2min 52s


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[1236  318   18  305  496]
 [ 659 6099  599  400  160]
 [  67  593 3561    6   44]
 [ 245  204   17 2751   75]
 [ 377   64    8   24 3365]]
              precision    recall  f1-score   support

           0       0.48      0.52      0.50      2373
           1       0.84      0.77      0.80      7917
           2       0.85      0.83      0.84      4271
           3       0.79      0.84      0.81      3292
           4       0.81      0.88      0.84      3838

    accuracy                           0.78     21691
   macro avg       0.75      0.77      0.76     21691
weighted avg       0.79      0.78      0.79     21691

Accurecy:  0.7842884145498132


#AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train, y_train)
y_pred = ada.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[2617  761  239 1904 2282]
 [ 712 3668 2138 1063  325]
 [ 145  811 6676  131   61]
 [1205  791  239 5428  340]
 [1068  132   82  356 6254]]
              precision    recall  f1-score   support

           0       0.46      0.34      0.39      7803
           1       0.60      0.46      0.52      7906
           2       0.71      0.85      0.78      7824
           3       0.61      0.68      0.64      8003
           4       0.68      0.79      0.73      7892

    accuracy                           0.63     39428
   macro avg       0.61      0.62      0.61     39428
weighted avg       0.61      0.63      0.61     39428

Accurecy:  0.6250126813432079


#Gradient_Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
grd = GradientBoostingClassifier()
grd.fit(X_train, y_train)
y_pred = grd.predict(X_test)

KeyboardInterrupt: ignored

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))