<a href="https://colab.research.google.com/github/FahmidaNourin/CSE445_Machine_Learning/blob/main/Project_Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#connecting with drive

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#read in csv file

In [6]:
import numpy as np
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/Sleep_Research/HMC_Sleep_Stages.csv")

In [7]:
df.head()

Subject Sleep_Stage  Epoch  MeanP_Alpha_F4  MedianF_Alpha_F4  \
0   SN002          N1      6         0.00034          10.11512   
1   SN002          N1      7         0.00035          10.73951   
2   SN002          N1      8         0.00035           9.36585   
3   SN002          N1    116         0.00054           9.74049   
4   SN002          N1    117         0.00034          10.11512   

   MeanF_Alpha_F4  SpectralEdge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0        17.85756               17.48293        10.24000        0.00047   
1        17.60780               17.10829         9.11610        0.00048   
2        17.60780               16.98341         9.24098        0.00042   
3        15.98439               15.48488         8.36683        0.00051   
4        16.48390               15.98439        12.23805        0.00034   

   MedianF_Beta_F4  ...  MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0         17.73268  ...         0.00112           0.74927         6.36878   
1         16.85854  ...         0.00070           0.99902         6.86829   
2         17.35805  ...         0.00077           1.49854         6.49366   
3         14.61073  ...         0.00082           0.87415         7.49268   
4         15.11024  ...         0.00084           0.87415         6.86829   

   SpectralEdge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  \
0                2.87220         0.62439        0.000076          32.71805   
1                3.62146         0.74927        0.000072          32.09366   
2                4.12098         0.74927        0.000069          33.09268   
3                3.49659         0.87415        0.000039          28.34732   
4                2.87220         0.62439        0.000032          28.97171   

   MeanF_Gamma_O2  SpectralEdge_Gamma_O2  PeakF_Gamma_O2  
0        43.83220               49.95122        49.95122  
1        44.33171               49.95122        49.95122  
2        43.95707               49.95122        49.95122  
3        43.08293               49.95122        49.95122  
4        43.20780               49.95122        49.95122  

[5 rows x 78 columns]

In [8]:
df.shape

(108451, 78)

In [9]:
df = df.loc[:,df.columns != "Subject"]
df = df.loc[:,df.columns != "Epoch"]

In [10]:
df

Sleep_Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0               N1         0.00034          10.11512        17.85756   
1               N1         0.00035          10.73951        17.60780   
2               N1         0.00035           9.36585        17.60780   
3               N1         0.00054           9.74049        15.98439   
4               N1         0.00034          10.11512        16.48390   
...            ...             ...               ...             ...   
108446           W         0.00042           9.99024        17.10829   
108447           W         0.00033          10.48976        16.60878   
108448           W         0.00064          10.48976        18.73171   
108449           W         0.00051          10.11512        17.85756   
108450           W         0.00128          10.61463        21.47902   

        SpectralEdge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  MedianF_Beta_F4  \
0                    17.48293        10.24000        0.00047         17.73268   
1                    17.10829         9.11610        0.00048         16.85854   
2                    16.98341         9.24098        0.00042         17.35805   
3                    15.48488         8.36683        0.00051         14.61073   
4                    15.98439        12.23805        0.00034         15.11024   
...                       ...             ...            ...              ...   
108446               16.35902         7.49268        0.00050         16.85854   
108447               16.10927         8.86634        0.00038         15.73463   
108448               18.48195         8.86634        0.00106         19.73073   
108449               17.48293        11.61366        0.00075         19.73073   
108450               21.35415         8.24195        0.00304         23.22732   

        MeanF_Beta_F4  SpectralEdge_Beta_F4  ...  MeanP_Delta_O2  \
0            25.35024              27.47317  ...         0.00112   
1            25.22537              26.97366  ...         0.00070   
2            26.09951              28.47220  ...         0.00077   
3            21.72878              22.47805  ...         0.00082   
4            22.10341              23.47707  ...         0.00084   
...               ...                   ...  ...             ...   
108446       26.22439              28.34732  ...         0.00070   
108447       24.35122              26.09951  ...         0.00106   
108448       29.09659              32.46829  ...         0.00106   
108449       29.72098              32.96780  ...         0.00508   
108450       33.21756              38.08780  ...         0.02494   

        MedianF_Delta_O2  MeanF_Delta_O2  SpectralEdge_Delta_O2  \
0                0.74927         6.36878                2.87220   
1                0.99902         6.86829                3.62146   
2                1.49854         6.49366                4.12098   
3                0.87415         7.49268                3.49659   
4                0.87415         6.86829                2.87220   
...                  ...             ...                    ...   
108446           1.12390         8.11707                4.99512   
108447           0.99902         6.86829                3.62146   
108448           0.74927         8.74146                4.12098   
108449           0.87415         5.36976                1.99805   
108450           0.87415         4.49561                2.12293   

        PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  MeanF_Gamma_O2  \
0              0.62439        0.000076          32.71805        43.83220   
1              0.74927        0.000072          32.09366        44.33171   
2              0.74927        0.000069          33.09268        43.95707   
3              0.87415        0.000039          28.34732        43.08293   
4              0.62439        0.000032          28.97171        43.20780   
...                ...             ...               ...             ...   
108446         

In [11]:
df = df.dropna().reset_index(drop=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108451 entries, 0 to 108450
Data columns (total 76 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Sleep_Stage            108451 non-null  object 
 1   MeanP_Alpha_F4         108451 non-null  float64
 2   MedianF_Alpha_F4       108451 non-null  float64
 3   MeanF_Alpha_F4         108451 non-null  float64
 4   SpectralEdge_Alpha_F4  108451 non-null  float64
 5   PeakF_Alpha_F4         108451 non-null  float64
 6   MeanP_Beta_F4          108451 non-null  float64
 7   MedianF_Beta_F4        108451 non-null  float64
 8   MeanF_Beta_F4          108451 non-null  float64
 9   SpectralEdge_Beta_F4   108451 non-null  float64
 10  PeakF_Beta_F4          108451 non-null  float64
 11  MeanP_Theta_F4         108451 non-null  float64
 12  MedianF_Theta_F4       108451 non-null  float64
 13  MeanF_Theta_F4         108451 non-null  float64
 14  SpectralEdge_Theta_F4  108451 non-nu

In [13]:
target="Sleep_Stage"

In [14]:
df["Sleep_Stage"].value_counts()

N2    39428
N3    21290
W     19355
R     16465
N1    11913
Name: Sleep_Stage, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
encd = LabelEncoder()

In [16]:
df["Sleep_Stage"] = encd.fit_transform(df["Sleep_Stage"])

In [18]:
df["Sleep_Stage"].value_counts()

1    39428
2    21290
4    19355
3    16465
0    11913
Name: Sleep_Stage, dtype: int64

In [19]:
target="Sleep_Stage"

In [20]:
X = df.loc[:,df.columns != target]
y = df[target]

In [21]:
!pip install imbalanced-learn

In [22]:
y.value_counts()

1    39428
2    21290
4    19355
3    16465
0    11913
Name: Sleep_Stage, dtype: int64

In [23]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_new,y_new = smote.fit_resample(X,y)

In [36]:
y_new.value_counts()

0    39428
1    39428
2    39428
3    39428
4    39428
Name: Sleep_Stage, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_new,y_new, test_size=0.20)

In [38]:
Y_train.value_counts()

4    31638
1    31577
0    31528
2    31493
3    31476
Name: Sleep_Stage, dtype: int64

In [39]:
Y_test.shape

(39428,)

# tree

In [43]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf=clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test,Y_pred))
print("Accurecy: ",accuracy_score(Y_test, Y_pred))

[[5552  756   97  710  785]
 [1036 4816 1055  712  232]
 [ 212  961 6642   64   56]
 [ 833  605   72 6290  152]
 [ 984  213   65  161 6367]]
              precision    recall  f1-score   support

           0       0.64      0.70      0.67      7900
           1       0.66      0.61      0.63      7851
           2       0.84      0.84      0.84      7935
           3       0.79      0.79      0.79      7952
           4       0.84      0.82      0.83      7790

    accuracy                           0.75     39428
   macro avg       0.75      0.75      0.75     39428
weighted avg       0.75      0.75      0.75     39428

Accurecy:  0.7524348178959115


#RandomForest

In [42]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)
Y_pred = rf.predict(X_test)

CPU times: user 2min 39s, sys: 280 ms, total: 2min 39s
Wall time: 2min 42s


In [45]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test,Y_pred))
print("Accurecy: ",accuracy_score(Y_test, Y_pred))

[[5552  756   97  710  785]
 [1036 4816 1055  712  232]
 [ 212  961 6642   64   56]
 [ 833  605   72 6290  152]
 [ 984  213   65  161 6367]]
              precision    recall  f1-score   support

           0       0.64      0.70      0.67      7900
           1       0.66      0.61      0.63      7851
           2       0.84      0.84      0.84      7935
           3       0.79      0.79      0.79      7952
           4       0.84      0.82      0.83      7790

    accuracy                           0.75     39428
   macro avg       0.75      0.75      0.75     39428
weighted avg       0.75      0.75      0.75     39428

Accurecy:  0.7524348178959115


#AdaBoost

In [46]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train, Y_train)
Y_pred = ada.predict(X_test)

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test,Y_pred))
print("Accurecy: ",accuracy_score(Y_test, Y_pred))

[[2914  834  268 1763 2121]
 [ 746 3335 2337 1135  298]
 [ 183  743 6796  126   87]
 [1253  807  240 5256  396]
 [1004  135   99  282 6270]]
              precision    recall  f1-score   support

           0       0.48      0.37      0.42      7900
           1       0.57      0.42      0.49      7851
           2       0.70      0.86      0.77      7935
           3       0.61      0.66      0.64      7952
           4       0.68      0.80      0.74      7790

    accuracy                           0.62     39428
   macro avg       0.61      0.62      0.61     39428
weighted avg       0.61      0.62      0.61     39428

Accurecy:  0.6231865679212742
