<a href="https://colab.research.google.com/github/FahmidaNourin/CSE445_Machine_Learning/blob/main/Project_Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#connecting with drive

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#read in csv file

In [69]:
import numpy as np
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/Sleep_Research/HMC_Sleep_Stages.csv")

In [30]:
df.head()

Subject Sleep_Stage  Epoch  MeanP_Alpha_F4  MedianF_Alpha_F4  \
0   SN002          N1      6         0.00034          10.11512   
1   SN002          N1      7         0.00035          10.73951   
2   SN002          N1      8         0.00035           9.36585   
3   SN002          N1    116         0.00054           9.74049   
4   SN002          N1    117         0.00034          10.11512   

   MeanF_Alpha_F4  SpectralEdge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0        17.85756               17.48293        10.24000        0.00047   
1        17.60780               17.10829         9.11610        0.00048   
2        17.60780               16.98341         9.24098        0.00042   
3        15.98439               15.48488         8.36683        0.00051   
4        16.48390               15.98439        12.23805        0.00034   

   MedianF_Beta_F4  ...  MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0         17.73268  ...         0.00112           0.74927         6.36878   
1         16.85854  ...         0.00070           0.99902         6.86829   
2         17.35805  ...         0.00077           1.49854         6.49366   
3         14.61073  ...         0.00082           0.87415         7.49268   
4         15.11024  ...         0.00084           0.87415         6.86829   

   SpectralEdge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  \
0                2.87220         0.62439        0.000076          32.71805   
1                3.62146         0.74927        0.000072          32.09366   
2                4.12098         0.74927        0.000069          33.09268   
3                3.49659         0.87415        0.000039          28.34732   
4                2.87220         0.62439        0.000032          28.97171   

   MeanF_Gamma_O2  SpectralEdge_Gamma_O2  PeakF_Gamma_O2  
0        43.83220               49.95122        49.95122  
1        44.33171               49.95122        49.95122  
2        43.95707               49.95122        49.95122  
3        43.08293               49.95122        49.95122  
4        43.20780               49.95122        49.95122  

[5 rows x 78 columns]

In [34]:
df = df.dropna().reset_index(drop=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108451 entries, 0 to 108450
Data columns (total 76 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Sleep_Stage            108451 non-null  object 
 1   MeanP_Alpha_F4         108451 non-null  float64
 2   MedianF_Alpha_F4       108451 non-null  float64
 3   MeanF_Alpha_F4         108451 non-null  float64
 4   SpectralEdge_Alpha_F4  108451 non-null  float64
 5   PeakF_Alpha_F4         108451 non-null  float64
 6   MeanP_Beta_F4          108451 non-null  float64
 7   MedianF_Beta_F4        108451 non-null  float64
 8   MeanF_Beta_F4          108451 non-null  float64
 9   SpectralEdge_Beta_F4   108451 non-null  float64
 10  PeakF_Beta_F4          108451 non-null  float64
 11  MeanP_Theta_F4         108451 non-null  float64
 12  MedianF_Theta_F4       108451 non-null  float64
 13  MeanF_Theta_F4         108451 non-null  float64
 14  SpectralEdge_Theta_F4  108451 non-nu

In [36]:
target="Sleep_Stage"

In [37]:
df["Sleep_Stage"].value_counts()

N2    39428
N3    21290
W     19355
R     16465
N1    11913
Name: Sleep_Stage, dtype: int64

In [38]:
from sklearn.preprocessing import LabelEncoder
encd = LabelEncoder()

In [39]:
df["Sleep_Stage"] = encd.fit_transform(df["Sleep_Stage"])

In [40]:
df["Sleep_Stage"].value_counts()

1    39428
2    21290
4    19355
3    16465
0    11913
Name: Sleep_Stage, dtype: int64

In [41]:
target="Sleep_Stage"

In [42]:
X = df.loc[:,df.columns != target]
y = df[target]

In [43]:
!pip install imbalanced-learn

In [44]:
y.value_counts()

1    39428
2    21290
4    19355
3    16465
0    11913
Name: Sleep_Stage, dtype: int64

In [45]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_new,y_new = smote.fit_resample(X,y)

In [46]:
y_new.value_counts()

0    39428
1    39428
2    39428
3    39428
4    39428
Name: Sleep_Stage, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new,y_new, test_size=0.20)

In [48]:
y_train.value_counts()

0    31625
2    31604
4    31536
1    31522
3    31425
Name: Sleep_Stage, dtype: int64

In [49]:
y_test.shape

(39428,)

# tree

In [50]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[5441  784  106  683  789]
 [ 978 4964 1045  666  253]
 [ 195  980 6536   71   42]
 [ 781  583   87 6398  154]
 [ 964  236   68  158 6466]]
              precision    recall  f1-score   support

           0       0.65      0.70      0.67      7803
           1       0.66      0.63      0.64      7906
           2       0.83      0.84      0.83      7824
           3       0.80      0.80      0.80      8003
           4       0.84      0.82      0.83      7892

    accuracy                           0.76     39428
   macro avg       0.76      0.76      0.76     39428
weighted avg       0.76      0.76      0.76     39428

Accurecy:  0.7559348686212843


#RandomForest

In [52]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

CPU times: user 3min 6s, sys: 595 ms, total: 3min 7s
Wall time: 3min 9s


In [53]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[6701  330   30  286  456]
 [ 657 6087  608  381  173]
 [ 118  501 7161    3   41]
 [ 360  166   18 7371   88]
 [ 486   42    6   28 7330]]
              precision    recall  f1-score   support

           0       0.81      0.86      0.83      7803
           1       0.85      0.77      0.81      7906
           2       0.92      0.92      0.92      7824
           3       0.91      0.92      0.92      8003
           4       0.91      0.93      0.92      7892

    accuracy                           0.88     39428
   macro avg       0.88      0.88      0.88     39428
weighted avg       0.88      0.88      0.88     39428

Accurecy:  0.8788170843055696


#AdaBoost

In [54]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train, y_train)
y_pred = ada.predict(X_test)

In [55]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[2617  761  239 1904 2282]
 [ 712 3668 2138 1063  325]
 [ 145  811 6676  131   61]
 [1205  791  239 5428  340]
 [1068  132   82  356 6254]]
              precision    recall  f1-score   support

           0       0.46      0.34      0.39      7803
           1       0.60      0.46      0.52      7906
           2       0.71      0.85      0.78      7824
           3       0.61      0.68      0.64      8003
           4       0.68      0.79      0.73      7892

    accuracy                           0.63     39428
   macro avg       0.61      0.62      0.61     39428
weighted avg       0.61      0.63      0.61     39428

Accurecy:  0.6250126813432079


#Gradient_Boosting

In [56]:
from sklearn.ensemble import GradientBoostingClassifier
grd = GradientBoostingClassifier()
grd.fit(X_train, y_train)
y_pred = grd.predict(X_test)

In [57]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[4460  570  127 1272 1374]
 [ 624 5586  933  542  221]
 [ 166  883 6678   40   57]
 [ 961  467  128 6272  175]
 [ 990  112   34  109 6647]]
              precision    recall  f1-score   support

           0       0.62      0.57      0.59      7803
           1       0.73      0.71      0.72      7906
           2       0.85      0.85      0.85      7824
           3       0.76      0.78      0.77      8003
           4       0.78      0.84      0.81      7892

    accuracy                           0.75     39428
   macro avg       0.75      0.75      0.75     39428
weighted avg       0.75      0.75      0.75     39428

Accurecy:  0.7518261134219336
