<a href="https://colab.research.google.com/github/FahmidaNourin/CSE445_Machine_Learning/blob/main/Project_Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#connecting with drive

In [61]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#read in csv file

In [62]:
import numpy as np
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/Sleep_Research/HMC_Sleep_Stages.csv")

In [63]:
df.head()

Subject Sleep_Stage  Epoch  MeanP_Alpha_F4  MedianF_Alpha_F4  \
0   SN002          N1      6         0.00034          10.11512   
1   SN002          N1      7         0.00035          10.73951   
2   SN002          N1      8         0.00035           9.36585   
3   SN002          N1    116         0.00054           9.74049   
4   SN002          N1    117         0.00034          10.11512   

   MeanF_Alpha_F4  SpectralEdge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0        17.85756               17.48293        10.24000        0.00047   
1        17.60780               17.10829         9.11610        0.00048   
2        17.60780               16.98341         9.24098        0.00042   
3        15.98439               15.48488         8.36683        0.00051   
4        16.48390               15.98439        12.23805        0.00034   

   MedianF_Beta_F4  ...  MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0         17.73268  ...         0.00112           0.74927         6.36878   
1         16.85854  ...         0.00070           0.99902         6.86829   
2         17.35805  ...         0.00077           1.49854         6.49366   
3         14.61073  ...         0.00082           0.87415         7.49268   
4         15.11024  ...         0.00084           0.87415         6.86829   

   SpectralEdge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  \
0                2.87220         0.62439        0.000076          32.71805   
1                3.62146         0.74927        0.000072          32.09366   
2                4.12098         0.74927        0.000069          33.09268   
3                3.49659         0.87415        0.000039          28.34732   
4                2.87220         0.62439        0.000032          28.97171   

   MeanF_Gamma_O2  SpectralEdge_Gamma_O2  PeakF_Gamma_O2  
0        43.83220               49.95122        49.95122  
1        44.33171               49.95122        49.95122  
2        43.95707               49.95122        49.95122  
3        43.08293               49.95122        49.95122  
4        43.20780               49.95122        49.95122  

[5 rows x 78 columns]

In [64]:
df = df.dropna().reset_index(drop=True)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108451 entries, 0 to 108450
Data columns (total 78 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Subject                108451 non-null  object 
 1   Sleep_Stage            108451 non-null  object 
 2   Epoch                  108451 non-null  int64  
 3   MeanP_Alpha_F4         108451 non-null  float64
 4   MedianF_Alpha_F4       108451 non-null  float64
 5   MeanF_Alpha_F4         108451 non-null  float64
 6   SpectralEdge_Alpha_F4  108451 non-null  float64
 7   PeakF_Alpha_F4         108451 non-null  float64
 8   MeanP_Beta_F4          108451 non-null  float64
 9   MedianF_Beta_F4        108451 non-null  float64
 10  MeanF_Beta_F4          108451 non-null  float64
 11  SpectralEdge_Beta_F4   108451 non-null  float64
 12  PeakF_Beta_F4          108451 non-null  float64
 13  MeanP_Theta_F4         108451 non-null  float64
 14  MedianF_Theta_F4       108451 non-nu

#Converting N1,N2 -> Light_Sleep, N3 -> Deep_Sleep And removing W stage.

In [66]:
df.shape

(108451, 78)

In [67]:
df =df.replace("N1", "Light_Sleep")
df =df.replace("N2", "Light_Sleep")
df =df.replace("N3", "Deep_Sleep")
df =df.replace("R", "REM")
df.drop(df.index[df['Sleep_Stage'] == "W"], inplace = True)


In [68]:
df.shape

(89096, 78)

#Removing columns

In [69]:
df = df.loc[:,df.columns != "Subject"]
df = df.loc[:,df.columns != "Epoch"]


#Encoding target columns (Sleep Stage)

In [70]:
target="Sleep_Stage"

In [71]:
df[target].value_counts()

Light_Sleep    51341
Deep_Sleep     21290
REM            16465
Name: Sleep_Stage, dtype: int64

In [72]:
from sklearn.preprocessing import LabelEncoder
encd = LabelEncoder()

In [73]:
df[target] = encd.fit_transform(df[target])

In [74]:
df[target].value_counts()

1    51341
0    21290
2    16465
Name: Sleep_Stage, dtype: int64

#Feature Selection: ANOVA

In [75]:
num_of_feat = 20

In [76]:

from sklearn.datasets import make_classification
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
import pandas as pd

X = df.loc[:,df.columns != "Sleep_Stage"]
y = df["Sleep_Stage"]

fs = SelectKBest(score_func=f_classif, k=5)
fit = fs.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

featureScores = pd.concat([dfcolumns,dfscores],axis=1)

featureScores.columns = ['Best_columns','Score_ANOVA']

lyst = featureScores.nlargest(num_of_feat,'Score_ANOVA')
ANOVA_feature=list(lyst['Best_columns'])
ANOVA_feature


['MeanF_Alpha_F4',
 'SpectralEdge_Alpha_F4',
 'MedianF_Alpha_O2',
 'MeanF_Delta_C4',
 'MeanF_Alpha_C4',
 'MeanF_Delta_F4',
 'MedianF_Alpha_F4',
 'SpectralEdge_Alpha_C4',
 'MeanF_Delta_O2',
 'SpectralEdge_Alpha_O2',
 'SpectralEdge_Beta_F4',
 'MeanF_Alpha_O2',
 'SpectralEdge_Beta_C4',
 'SpectralEdge_Delta_C4',
 'MedianF_Beta_F4',
 'PeakF_Beta_F4',
 'SpectralEdge_Theta_O2',
 'PeakF_Beta_C4',
 'SpectralEdge_Delta_F4',
 'SpectralEdge_Delta_O2']

#Pearson’s

In [77]:

from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
import pandas as pd
X = df.loc[:,df.columns != "Sleep_Stage"]
y = df["Sleep_Stage"]
fs = SelectKBest(score_func=f_regression, k=5)
fit = fs.fit(X,y)

#create df for scores
dfscores = pd.DataFrame(fit.scores_)
#create df for column names
dfcolumns = pd.DataFrame(df.columns)
#concat two dataframes for better visualization
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
#naming the dataframe columns
featureScores.columns = ['Best_columns','Score_pearsons']

#print 10 best features
lyst = featureScores.nlargest(num_of_feat,'Score_pearsons')

PEARSON_feature=list(lyst['Best_columns'])
PEARSON_feature


['MedianF_Alpha_F4',
 'MeanF_Alpha_F4',
 'MedianF_Alpha_C4',
 'MeanP_Alpha_O2',
 'MeanF_Alpha_C4',
 'MedianF_Delta_C4',
 'MedianF_Delta_F4',
 'MedianF_Delta_O2',
 'MeanF_Alpha_O2',
 'MedianF_Alpha_O2',
 'MeanF_Beta_F4',
 'SpectralEdge_Beta_F4',
 'MeanF_Beta_C4',
 'MeanP_Beta_F4',
 'MeanF_Delta_C4',
 'SpectralEdge_Beta_C4',
 'MeanF_Delta_F4',
 'MedianF_Beta_C4',
 'MedianF_Beta_F4',
 'MeanF_Theta_O2']

#Univarient Feature Selection

In [78]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)


#concat two dataframes for better visualization
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns



sorted_df = featureScores.sort_values(by=['Score'], ascending=False)
Univarient_feature = sorted_df["Specs"][:num_of_feat]
Univarient_feature

9             PeakF_Beta_F4
34            PeakF_Beta_C4
6           MedianF_Beta_F4
8      SpectralEdge_Beta_F4
33     SpectralEdge_Beta_C4
31          MedianF_Beta_C4
3     SpectralEdge_Alpha_F4
2            MeanF_Alpha_F4
32            MeanF_Beta_C4
7             MeanF_Beta_F4
42           MeanF_Delta_C4
56          MedianF_Beta_O2
54           PeakF_Alpha_O2
27           MeanF_Alpha_C4
28    SpectralEdge_Alpha_C4
17           MeanF_Delta_F4
63    SpectralEdge_Theta_O2
43    SpectralEdge_Delta_C4
36         MedianF_Theta_C4
67           MeanF_Delta_O2
Name: Specs, dtype: object

#Spliting Dataset into X(features) and y(target)

In [79]:
from scipy.stats import pearson3
#X = df.loc[:,df.columns != target]
#X = df.loc[:,ANOVA_feature]
#X = df.loc[:,Univarient_feature]
X = df.loc[:,PEARSON_feature]
y = df[target]




#Scaling Dataset

In [80]:
X

MedianF_Alpha_F4  MeanF_Alpha_F4  MedianF_Alpha_C4  MeanP_Alpha_O2  \
0              10.11512        17.85756           9.86537         0.00023   
1              10.73951        17.60780          10.48976         0.00023   
2               9.36585        17.60780           8.99122         0.00025   
3               9.74049        15.98439          10.24000         0.00029   
4              10.11512        16.48390           9.86537         0.00020   
...                 ...             ...               ...             ...   
89091           9.36585        17.60780           9.61561         0.00023   
89092          10.36488        20.10537          10.61463         0.00044   
89093          10.24000        18.48195          10.73951         0.00046   
89094           9.24098        16.48390           9.24098         0.00032   
89095           9.24098        16.98341           9.74049         0.00031   

       MeanF_Alpha_C4  MedianF_Delta_C4  MedianF_Delta_F4  MedianF_Delta_O2  \
0            18.48195           0.87415           0.74927           0.74927   
1            19.60585           0.87415           0.74927           0.99902   
2            17.35805           1.62341           0.99902           1.49854   
3            17.10829           0.87415           0.74927           0.87415   
4            17.10829           0.74927           0.62439           0.87415   
...               ...               ...               ...               ...   
89091        17.23317           1.37366           0.99902           0.99902   
89092        20.35512           0.99902           0.49951           0.49951   
89093        18.73171           0.99902           0.74927           0.74927   
89094        16.23415           1.49854           0.62439           0.62439   
89095        16.73366           1.99805           0.74927           0.74927   

       MeanF_Alpha_O2  MedianF_Alpha_O2  MeanF_Beta_F4  SpectralEdge_Beta_F4  \
0            18.48195          10.61463       25.35024              27.47317   
1            18.10732          10.36488       25.22537              26.97366   
2            17.35805           9.74049       26.09951              28.47220   
3            16.73366           9.49073       21.72878              22.47805   
4            17.10829           9.99024       22.10341              23.47707   
...               ...               ...            ...                   ...   
89091        17.60780           9.36585       22.72780              24.10146   
89092        20.10537          10.36488       30.22049              35.34049   
89093        18.48195          10.24000       27.59805              30.34537   
89094        16.48390           9.24098       23.97659              24.97561   
89095        16.98341           9.24098       22.85268              23.60195   

       MeanF_Beta_C4  MeanP_Beta_F4  MeanF_Delta_C4  SpectralEdge_Beta_C4  \
0           25.84976        0.00047         6.74341              27.22341   
1           25.84976        0.00048         6.61854              27.09854   
2           26.34927        0.00042         6.36878              27.97268   
3           22.22829        0.00051         7.61756              23.10244   
4           22.85268        0.00034         6.49366              23.85171   
...              ...            ...             ...                   ...   
89091       23.10244        0.00026         6.24390              24.35122   
89092       30.47024        0.00083         6.61854              35.46537   
89093       27.59805        0.00066         6.99317              30.47024   
89094       22.60293        0.00030         6.61854              23.97659   
89095       22.72780        0.00032         6.36878              23.60195   

       MeanF_Delta_F4  MedianF_Beta_C4  MedianF_Beta_F4  MeanF_Theta_O2  
0             6.61854         18.85659         17.73268        12.98732  
1             6.61854         19.35610         16.85854        12.86244  
2             6.61854    

In [81]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X[X.columns] =   scaler.transform(X)

In [82]:
X

MedianF_Alpha_F4  MeanF_Alpha_F4  MedianF_Alpha_C4  MeanP_Alpha_O2  \
0              0.630879        0.703047          0.188717       -0.090035   
1              0.969324        0.638237          0.362572       -0.090035   
2              0.224744        0.638237         -0.054681       -0.086551   
3              0.427814        0.216977          0.293029       -0.079583   
4              0.630879        0.346595          0.188717       -0.095261   
...                 ...             ...               ...             ...   
89091          0.224744        0.638237          0.119174       -0.090035   
89092          0.766260        1.286333          0.397340       -0.053453   
89093          0.698569        0.865071          0.432112       -0.049970   
89094          0.157059        0.346595          0.014862       -0.074357   
89095          0.157059        0.476214          0.153946       -0.076099   

       MeanF_Alpha_C4  MedianF_Delta_C4  MedianF_Delta_F4  MedianF_Delta_O2  \
0            0.578725         -0.199981         -0.201811         -0.187368   
1            0.803059         -0.199981         -0.201811         -0.118640   
2            0.354390          0.006967         -0.132965          0.018821   
3            0.304537         -0.199981         -0.201811         -0.153003   
4            0.304537         -0.234473         -0.236236         -0.153003   
...               ...               ...               ...               ...   
89091        0.329464         -0.062015         -0.132965         -0.118640   
89092        0.952615         -0.165491         -0.270661         -0.256099   
89093        0.628577         -0.165491         -0.201811         -0.187368   
89094        0.130056         -0.027523         -0.236236         -0.221733   
89095        0.229760          0.110443         -0.201811         -0.187368   

       MeanF_Alpha_O2  MedianF_Alpha_O2  MeanF_Beta_F4  SpectralEdge_Beta_F4  \
0            0.516306          0.616104      -0.106329             -0.080005   
1            0.447183          0.528886      -0.115262             -0.114617   
2            0.308936          0.310837      -0.052727             -0.010780   
3            0.193731          0.223616      -0.365405             -0.426128   
4            0.262854          0.398055      -0.338604             -0.356904   
...               ...               ...            ...                   ...   
89091        0.355017          0.180006      -0.293936             -0.313638   
89092        0.815841          0.528886       0.242084              0.465139   
89093        0.516306          0.485276       0.054477              0.119016   
89094        0.147648          0.136399      -0.204599             -0.253066   
89095        0.239812          0.136399      -0.285002             -0.348250   

       MeanF_Beta_C4  MeanP_Beta_F4  MeanF_Delta_C4  SpectralEdge_Beta_C4  \
0          -0.090191      -0.079722        0.149598             -0.114727   
1          -0.090191      -0.077219        0.113126             -0.123063   
2          -0.055935      -0.092232        0.040177             -0.064705   
3          -0.338545      -0.069713        0.404916             -0.389846   
4          -0.295725      -0.112249        0.076652             -0.339824   
...              ...            ...             ...                   ...   
89091      -0.278597      -0.132266        0.003703             -0.306477   
89092       0.226673       0.010355        0.113126              0.435514   
89093       0.029704      -0.032181        0.222547              0.102034   
89094      -0.312852      -0.122258        0.113126             -0.331487   
89095      -0.304289      -0.117253        0.040177             -0.356499   

       MeanF_Delta_F4  MedianF_Beta_C4  MedianF_Beta_F4  MeanF_Theta_O2  
0            0.187936         0.074183         0.070094        0.174107  
1            0.187936         0.106778         0.009672        0.155682  
2            0.187936    

#Spliting X and y to train and test sets

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20)

In [84]:
y_train.value_counts()

1    41114
0    16960
2    13202
Name: Sleep_Stage, dtype: int64

#Oversampling using SMOTE

**<font color='red'>SNB:</font><font color='olive'> We used *SMOTE* in train data only, so that our test data can remain corrupted data free. The accurecy of the model will be counted only for actual data.</font>**

In [85]:
!pip install imbalanced-learn

In [86]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train,y_train = smote.fit_resample(X_train,y_train)

In [87]:
y_train.value_counts()

0    41114
1    41114
2    41114
Name: Sleep_Stage, dtype: int64

In [88]:
y_test.value_counts()

1    10227
0     4330
2     3263
Name: Sleep_Stage, dtype: int64

#RandomForest

In [89]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

CPU times: user 1min 4s, sys: 214 ms, total: 1min 4s
Wall time: 1min 24s


In [90]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[3514  802   14]
 [ 750 8695  782]
 [  22  757 2484]]
              precision    recall  f1-score   support

           0       0.82      0.81      0.82      4330
           1       0.85      0.85      0.85     10227
           2       0.76      0.76      0.76      3263

    accuracy                           0.82     17820
   macro avg       0.81      0.81      0.81     17820
weighted avg       0.82      0.82      0.82     17820

Accurecy:  0.8245230078563411


#AdaBoost

In [91]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train, y_train)
y_pred = ada.predict(X_test)

In [92]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[3483  761   86]
 [1853 5934 2440]
 [  82  745 2436]]
              precision    recall  f1-score   support

           0       0.64      0.80      0.71      4330
           1       0.80      0.58      0.67     10227
           2       0.49      0.75      0.59      3263

    accuracy                           0.67     17820
   macro avg       0.64      0.71      0.66     17820
weighted avg       0.70      0.67      0.67     17820

Accurecy:  0.6651515151515152


#Gradient_Boosting

In [93]:
from sklearn.ensemble import GradientBoostingClassifier
grd = GradientBoostingClassifier()
grd.fit(X_train, y_train)
y_pred = grd.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[3334  887   27]
 [1144 7773 1316]
 [  47 1032 2260]]
              precision    recall  f1-score   support

           0       0.74      0.78      0.76      4248
           1       0.80      0.76      0.78     10233
           2       0.63      0.68      0.65      3339

    accuracy                           0.75     17820
   macro avg       0.72      0.74      0.73     17820
weighted avg       0.75      0.75      0.75     17820

Accurecy:  0.7501122334455668


#XGBOOSTING


In [94]:
from xgboost import XGBClassifier

In [95]:
# fit model no training data
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [97]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[3414  908    8]
 [ 662 8867  698]
 [  18  969 2276]]
              precision    recall  f1-score   support

           0       0.83      0.79      0.81      4330
           1       0.83      0.87      0.85     10227
           2       0.76      0.70      0.73      3263

    accuracy                           0.82     17820
   macro avg       0.81      0.78      0.80     17820
weighted avg       0.82      0.82      0.82     17820

Accurecy:  0.8168911335578002
